[build]
  cmd = "templ generate && go build -o ./tmp/main ./src"
  bin = "tmp/main"
  include_ext = ["go", "templ"]
  exclude_regex = ["_templ.go"]
  exclude_dir = ["assets", "tmp"]

[log]
  time = true

[misc]
  clean_on_exit = true
